name: VOLTSMP
version: '1.0-SNAPSHOT'
main: me.VoltMC.VoltSMP.Main
api-version: '1.21'


commands:
  testgui:
    description: "testing"
  playtime:
    description: "Display Total Playtime on the Server"
    aliases:
      - pt
      - playt
      - time